-- Run STEP 8: Wian 12 SQM 2 Side Open Stall Exhibition Stall Design at FIT

INSERT INTO projects (title,slug,stall_area_sqm,stall_area_sqft,stall_height_m,floors,build_year,city,exhibition_id,client_id,description,design_brief,ai_summary,design_style,materials_used,special_features,awards,status,is_featured,display_order) VALUES ('Wian 12 SQM 2 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025','wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025',12,129.17,4,1,2025,'Gandhinagar',(SELECT id FROM exhibitions WHERE slug='fitag-tech-expo-it-show'),(SELECT id FROM clients WHERE slug='wian'),'Approach Media designed and fabricated a 12 SQM 2 side open stall exhibition stall for Wian at FITAG Tech Expo - IT Show, Helipad Ground, Gandhinagar. The booth presents a compact Wian stall with a blue-white illuminated fascia, product display cabinet, consultation counter, and a tidy two-side open technology display format. The stall was planned for strong brand recall, clear product visibility, easy visitor movement, and search-friendly portfolio discovery for security devises, it, hardware, television exhibition projects in Gandhinagar, India.','Create a 12 SQM 2 side open stall custom exhibition stall for Wian that communicates technology, product credibility, and visitor engagement at FITAG Tech Expo - IT Show. The design needed visible branding, product-led storytelling, practical discussion areas, and a premium finish suitable for a busy expo environment.','Wian exhibition stall by Approach Media at FITAG Tech Expo - IT Show, Gandhinagar: 12 SQM 2 side open stall booth with compact blue-white technology display booth, designed for product display, lead generation, visitor interaction, and high search relevance around custom exhibition stall design and fabrication in Gujarat.','Compact blue-white technology display booth','["Wooden modular panels", "laminate finish", "printed vinyl graphics", "acrylic signage", "LED lighting", "display shelves"]','["Two-side open compact stall", "illuminated blue fascia", "product display counter", "wall graphics", "visitor interaction desk"]',NULL,'published',true,70) ON CONFLICT (slug) DO NOTHING;
INSERT INTO seo_metadata (project_id,meta_title,meta_description,og_title,og_description,og_image_url) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'Wian 12 SQM Stall Design | FITAG Tech Expo - IT Show','Explore Wian''s 12 SQM 2 side open stall exhibition stall at FITAG Tech Expo - IT Show, Gandhinagar, designed and fabricated by Approach Media for impactful','Wian Custom Exhibition Stall at FITAG Tech Expo - IT Show','12 SQM 2 side open stall exhibition stall design and fabrication for Wian by Approach Media at FITAG Tech Expo - IT Show, Helipad Ground, Gandhinagar.','2025/fitag-tech-expo-it-show/wian/wian-fitag-tech-expo-it-show-gandhinagar-12-sqm-2-side-open-stall-exhibition-stall-design-fabrication-approach-media-01.webp') ON CONFLICT (project_id) DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,caption,display_order,is_hero,is_thumbnail) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/wian/wian-fitag-tech-expo-it-show-gandhinagar-12-sqm-2-side-open-stall-exhibition-stall-design-fabrication-approach-media-01.webp','Wian 12 SQM 2 side open stall exhibition stall design at FITAG Tech Expo - IT Show Gandhinagar by Approach Media','Wian 12 SQM 2 Side Open Stall exhibition stall at FITAG Tech Expo - IT Show, Helipad Ground, Gandhinagar, designed and fabricated by Approach Media.',0,true,true) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/wian/wian-fitag-tech-expo-it-show-gandhinagar-12-sqm-2-side-open-stall-exhibition-stall-design-fabrication-approach-media-02.webp','Wian 12 SQM 2 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 1',1) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/wian/wian-fitag-tech-expo-it-show-gandhinagar-12-sqm-2-side-open-stall-exhibition-stall-design-fabrication-approach-media-03.webp','Wian 12 SQM 2 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 2',2) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/wian/wian-fitag-tech-expo-it-show-gandhinagar-12-sqm-2-side-open-stall-exhibition-stall-design-fabrication-approach-media-04.webp','Wian 12 SQM 2 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 3',3) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/wian/wian-fitag-tech-expo-it-show-gandhinagar-12-sqm-2-side-open-stall-exhibition-stall-design-fabrication-approach-media-05.webp','Wian 12 SQM 2 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 4',4) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/wian/wian-fitag-tech-expo-it-show-gandhinagar-12-sqm-2-side-open-stall-exhibition-stall-design-fabrication-approach-media-06.webp','Wian 12 SQM 2 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 5',5) ON CONFLICT DO NOTHING;
INSERT INTO project_industries (project_id,industry_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM industries WHERE slug='security-devises'),true) ON CONFLICT DO NOTHING;
INSERT INTO project_industries (project_id,industry_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM industries WHERE slug='it'),false) ON CONFLICT DO NOTHING;
INSERT INTO project_industries (project_id,industry_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM industries WHERE slug='hardware'),false) ON CONFLICT DO NOTHING;
INSERT INTO project_industries (project_id,industry_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM industries WHERE slug='television'),false) ON CONFLICT DO NOTHING;
INSERT INTO project_stall_types (project_id,stall_type_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='wian-12-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM stall_types WHERE slug='2-side-open-stall'),true) ON CONFLICT DO NOTHING;
