-- Run STEP 3: Acrrynics 18 SQM 3 Side Open Stall Exhibition Stall Design a

INSERT INTO projects (title,slug,stall_area_sqm,stall_area_sqft,stall_height_m,floors,build_year,city,exhibition_id,client_id,description,design_brief,ai_summary,design_style,materials_used,special_features,awards,status,is_featured,display_order) VALUES ('Acrrynics 18 SQM 3 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025','acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025',18,193.75,4,1,2025,'Gandhinagar',(SELECT id FROM exhibitions WHERE slug='fitag-tech-expo-it-show'),(SELECT id FROM clients WHERE slug='acrrynics'),'Approach Media designed and fabricated an 18 SQM 3 side open stall exhibition stall for Acrrynics at FITAG Tech Expo - IT Show, Helipad Ground, Gandhinagar. The booth presents a compact Acronis and Nilmay branded IT security exhibit with illuminated counters, cyber cloud communication panels, blue flooring, and a clean meeting-led layout. The stall was planned for strong brand recall, clear product visibility, easy visitor movement, and search-friendly portfolio discovery for security devises, it, hardware, television exhibition projects in Gandhinagar, India.','Create an 18 SQM 3 side open stall custom exhibition stall for Acrrynics that communicates technology, product credibility, and visitor engagement at FITAG Tech Expo - IT Show. The design needed visible branding, product-led storytelling, practical discussion areas, and a premium finish suitable for a busy expo environment.','Acrrynics exhibition stall by Approach Media at FITAG Tech Expo - IT Show, Gandhinagar: 18 SQM 3 side open stall booth with clean technology booth with blue-white cyber security branding, designed for product display, lead generation, visitor interaction, and high search relevance around custom exhibition stall design and fabrication in Gujarat.','Clean technology booth with blue-white cyber security branding','["Laminated wooden structure", "printed vinyl graphics", "acrylic logo panels", "LED backlit fascia", "carpet flooring", "display lighting"]','["Backlit fascia", "Acronis/Nilmay brand panels", "product communication wall", "meeting seating", "illuminated counter", "open visitor access"]',NULL,'published',true,20) ON CONFLICT (slug) DO NOTHING;
INSERT INTO seo_metadata (project_id,meta_title,meta_description,og_title,og_description,og_image_url) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'Acrrynics 18 SQM Stall Design | FITAG Tech Expo - IT Show','Explore Acrrynics''s 18 SQM 3 side open stall exhibition stall at FITAG Tech Expo - IT Show, Gandhinagar, designed and fabricated by Approach Media for','Acrrynics Custom Exhibition Stall at FITAG Tech Expo - IT Show','18 SQM 3 side open stall exhibition stall design and fabrication for Acrrynics by Approach Media at FITAG Tech Expo - IT Show, Helipad Ground, Gandhinagar.','2025/fitag-tech-expo-it-show/acrrynics/acrrynics-fitag-tech-expo-it-show-gandhinagar-18-sqm-3-side-open-stall-exhibition-stall-design-fabrication-approach-media-01.webp') ON CONFLICT (project_id) DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,caption,display_order,is_hero,is_thumbnail) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/acrrynics/acrrynics-fitag-tech-expo-it-show-gandhinagar-18-sqm-3-side-open-stall-exhibition-stall-design-fabrication-approach-media-01.webp','Acrrynics 18 SQM 3 side open stall exhibition stall design at FITAG Tech Expo - IT Show Gandhinagar by Approach Media','Acrrynics 18 SQM 3 Side Open Stall exhibition stall at FITAG Tech Expo - IT Show, Helipad Ground, Gandhinagar, designed and fabricated by Approach Media.',0,true,true) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/acrrynics/acrrynics-fitag-tech-expo-it-show-gandhinagar-18-sqm-3-side-open-stall-exhibition-stall-design-fabrication-approach-media-02.webp','Acrrynics 18 SQM 3 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 1',1) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/acrrynics/acrrynics-fitag-tech-expo-it-show-gandhinagar-18-sqm-3-side-open-stall-exhibition-stall-design-fabrication-approach-media-03.webp','Acrrynics 18 SQM 3 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 2',2) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/acrrynics/acrrynics-fitag-tech-expo-it-show-gandhinagar-18-sqm-3-side-open-stall-exhibition-stall-design-fabrication-approach-media-04.webp','Acrrynics 18 SQM 3 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 3',3) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/acrrynics/acrrynics-fitag-tech-expo-it-show-gandhinagar-18-sqm-3-side-open-stall-exhibition-stall-design-fabrication-approach-media-05.webp','Acrrynics 18 SQM 3 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 4',4) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/acrrynics/acrrynics-fitag-tech-expo-it-show-gandhinagar-18-sqm-3-side-open-stall-exhibition-stall-design-fabrication-approach-media-06.webp','Acrrynics 18 SQM 3 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 5',5) ON CONFLICT DO NOTHING;
INSERT INTO media (project_id,media_type,url,alt_text,display_order) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),'image','2025/fitag-tech-expo-it-show/acrrynics/acrrynics-fitag-tech-expo-it-show-gandhinagar-18-sqm-3-side-open-stall-exhibition-stall-design-fabrication-approach-media-07.webp','Acrrynics 18 SQM 3 Side Open Stall Exhibition Stall Design at FITAG Tech Expo - IT Show, Gandhinagar 2025 photo 6',6) ON CONFLICT DO NOTHING;
INSERT INTO project_industries (project_id,industry_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM industries WHERE slug='security-devises'),true) ON CONFLICT DO NOTHING;
INSERT INTO project_industries (project_id,industry_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM industries WHERE slug='it'),false) ON CONFLICT DO NOTHING;
INSERT INTO project_industries (project_id,industry_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM industries WHERE slug='hardware'),false) ON CONFLICT DO NOTHING;
INSERT INTO project_industries (project_id,industry_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM industries WHERE slug='television'),false) ON CONFLICT DO NOTHING;
INSERT INTO project_stall_types (project_id,stall_type_id,is_primary) VALUES ((SELECT id FROM projects WHERE slug='acrrynics-18-sqm-custom-exhibition-stall-fitag-tech-expo-it-show-gandhinagar-2025'),(SELECT id FROM stall_types WHERE slug='3-side-open-stall'),true) ON CONFLICT DO NOTHING;
